# Generated by Django 4.2.2 on 2024-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qr_scanner_master',
            fields=[
                ('qr_scanner_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('qr_scanned_name', models.CharField(max_length=150, null=True)),
                ('qr_scanned_password', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
