# Generated by Django 4.2.2 on 2024-05-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qr_scanner_master',
            new_name='qr_scanner_login',
        ),
    ]
