# Generated by Django 4.2.1 on 2024-05-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qr_scanner_master',
            fields=[
                ('qr_scanner_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('qr_scanner_sl_number', models.CharField(max_length=150, unique=True)),
                ('qr_scanner_scanned_date', models.DateField(auto_now_add=True, null=True)),
                ('qr_scanner_scanned_by', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
