# Generated by Django 4.2.1 on 2024-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_scanner_master',
            name='qr_scanner_scanned_by',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
