# Generated by Django 4.2.1 on 2024-05-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0002_alter_qr_scanner_master_qr_scanner_scanned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_scanner_master',
            name='qr_scanner_sl_number',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
