# Generated by Django 4.2.1 on 2024-05-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0003_alter_qr_scanner_master_qr_scanner_sl_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_scanner_master',
            old_name='qr_scanner_scanned_by',
            new_name='qr_scanned_by',
        ),
        migrations.RenameField(
            model_name='qr_scanner_master',
            old_name='qr_scanner_scanned_date',
            new_name='qr_scanned_date',
        ),
        migrations.RenameField(
            model_name='qr_scanner_master',
            old_name='qr_scanner_sl_number',
            new_name='qr_scanned_sl_number',
        ),
    ]
