# Generated by Django 4.2 on 2024-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0004_rename_qr_scanner_scanned_by_qr_scanner_master_qr_scanned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_scanner_master',
            name='qr_scanned_by',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='qr_scanner_master',
            name='qr_scanned_sl_number',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
