# Generated by Django 4.2.1 on 2024-06-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0005_alter_qr_scanner_master_qr_scanned_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder_Store',
            fields=[
                ('cylinder_db_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('vendor_name', models.CharField()),
                ('cylinder_sl_r_qr_no', models.CharField()),
                ('cylinder_scanned_r_received_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cylinder_scanned_r_received_by', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='qr_scanner_master',
        ),
    ]
