# Generated by Django 4.2.1 on 2024-06-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0006_cylinder_store_delete_qr_scanner_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinder_store',
            old_name='vendor_name',
            new_name='cylinder_vendor_name',
        ),
    ]
