# Generated by Django 4.2.1 on 2024-06-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0007_rename_vendor_name_cylinder_store_cylinder_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder_Type_Master',
            fields=[
                ('cylinder_type_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cylinder_gas_type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cyliner_Inward',
            fields=[
                ('cylinder_inward_db_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_Inward',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_Outward',
            field=models.BooleanField(default=None),
        ),
    ]
