# Generated by Django 4.2.1 on 2024-06-18 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0008_cylinder_type_master_cyliner_inward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_gas_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET, to='QR.cylinder_type_master'),
        ),
    ]
