# Generated by Django 4.2.1 on 2024-06-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0009_cylinder_store_cylinder_gas_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_Cylinder_Vendors_Master',
            fields=[
                ('gas_cylinder_vendor_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('gas_cylinder_vendor_name', models.CharField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cylinder_type_master',
            name='cylinder_gas_type',
            field=models.CharField(unique=True),
        ),
    ]
