# Generated by Django 4.2.1 on 2024-06-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0010_gas_cylinder_vendors_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_vendor_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET, to='QR.gas_cylinder_vendors_master'),
        ),
    ]
