# Generated by Django 4.2.1 on 2024-06-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0011_alter_cylinder_store_cylinder_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_Inward',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_Outward',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
