# Generated by Django 4.2.1 on 2024-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0012_alter_cylinder_store_cylinder_inward_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cyliner_Inward',
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_stocked',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
