# Generated by Django 4.2.1 on 2024-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0013_delete_cyliner_inward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_Inward',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_Outward',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_stocked',
            field=models.BooleanField(default=False),
        ),
    ]
