# Generated by Django 4.2.1 on 2024-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0014_alter_cylinder_store_cylinder_inward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_sl_r_qr_no',
            field=models.CharField(unique=True),
        ),
    ]
