# Generated by Django 4.2.1 on 2024-06-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0015_alter_cylinder_store_cylinder_sl_r_qr_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cylinder_Store',
        ),
    ]
