# Generated by Django 4.2.1 on 2024-06-18 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0016_delete_cylinder_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder_Store',
            fields=[
                ('cylinder_db_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cylinder_sl_r_qr_no', models.CharField(unique=True)),
                ('cylinder_scanned_r_received_date', models.DateTimeField(default=None, null=True)),
                ('cylinder_scanned_r_received_by', models.CharField(max_length=300)),
                ('cylinder_Inward', models.BooleanField(default=False)),
                ('cylinder_Inward_Date', models.DateTimeField()),
                ('cylinder_Outward', models.BooleanField(default=False)),
                ('cylinder_Outward_Date', models.DateTimeField()),
                ('cylinder_stocked', models.BooleanField(default=False)),
                ('cylinder_stocked_Date', models.DateTimeField()),
                ('cylinder_gas_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET, to='QR.cylinder_type_master')),
                ('cylinder_vendor_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET, to='QR.gas_cylinder_vendors_master')),
            ],
        ),
    ]
