# Generated by Django 4.2.1 on 2024-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0017_cylinder_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_Inward_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_Outward_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_stocked_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
