# Generated by Django 4.2.1 on 2024-06-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0018_alter_cylinder_store_cylinder_inward_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinder_store',
            old_name='cylinder_scanned_r_received_by',
            new_name='cylinder_scanned_r_submitted_by',
        ),
        migrations.RenameField(
            model_name='cylinder_store',
            old_name='cylinder_scanned_r_received_date',
            new_name='cylinder_scanned_r_submitted_date',
        ),
        migrations.RenameField(
            model_name='cylinder_type_master',
            old_name='cylinder_gas_type',
            new_name='cylinder_gas_type_description',
        ),
    ]
