# Generated by Django 4.2.1 on 2024-06-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0019_rename_cylinder_scanned_r_received_by_cylinder_store_cylinder_scanned_r_submitted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinder_type_master',
            old_name='cylinder_gas_type_description',
            new_name='cylinder_gas_type',
        ),
    ]
