# Generated by Django 4.2.1 on 2024-06-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0020_rename_cylinder_gas_type_description_cylinder_type_master_cylinder_gas_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinder_store',
            old_name='cylinder_stocked',
            new_name='cylinder_stocked_in',
        ),
        migrations.RenameField(
            model_name='cylinder_store',
            old_name='cylinder_stocked_Date',
            new_name='cylinder_stocked_in_Date',
        ),
    ]
