# Generated by Django 4.2.1 on 2024-06-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0021_rename_cylinder_stocked_cylinder_store_cylinder_stocked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_stock_ot_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_stock_out',
            field=models.BooleanField(default=False),
        ),
    ]
