# Generated by Django 4.2.1 on 2024-06-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0022_cylinder_store_cylinder_stock_ot_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinder_store',
            old_name='cylinder_stock_ot_Date',
            new_name='cylinder_stock_out_Date',
        ),
    ]
