# Generated by Django 4.2.1 on 2024-06-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0023_rename_cylinder_stock_ot_date_cylinder_store_cylinder_stock_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_GRN_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_GRN_no',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_Invoice_DC_no',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_description',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_po_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_po_no',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_remarks',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='cylinder_return_DC',
            field=models.CharField(null=True),
        ),
    ]
