# Generated by Django 4.2.1 on 2024-06-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0024_cylinder_store_cylinder_grn_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder_Inward_Details',
            fields=[
                ('cylinder_inward_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cylinder_po_no', models.CharField()),
                ('cylinder_po_Date', models.DateTimeField()),
                ('cylinder_GRN_no', models.CharField()),
                ('cylinder_GRN_Date', models.DateTimeField()),
                ('cylinder_Invoice_DC_no', models.CharField()),
                ('cylinder_description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder_Outward_Details',
            fields=[
                ('cylinder_outward_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cylinder_return_dc', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_GRN_Date',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_GRN_no',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_Invoice_DC_no',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_description',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_po_Date',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_po_no',
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='Cylinder_Inward_Table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='QR.cylinder_inward_details'),
        ),
        migrations.AddField(
            model_name='cylinder_store',
            name='Cylinder_Outward_Table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='QR.cylinder_outward_details'),
        ),
    ]
