# Generated by Django 4.2.1 on 2024-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0025_cylinder_inward_details_cylinder_outward_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinder_outward_details',
            old_name='cylinder_return_dc',
            new_name='cylinder_return_DC',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_remarks',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_return_DC',
        ),
        migrations.AddField(
            model_name='cylinder_outward_details',
            name='cylinder_remarks',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cylinder_inward_details',
            name='cylinder_GRN_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cylinder_inward_details',
            name='cylinder_po_Date',
            field=models.DateField(),
        ),
    ]
