# Generated by Django 4.2.1 on 2024-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0026_rename_cylinder_return_dc_cylinder_outward_details_cylinder_return_dc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder_inward_details',
            name='cylinder_GRN_no',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='cylinder_inward_details',
            name='cylinder_Invoice_DC_no',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='cylinder_inward_details',
            name='cylinder_po_no',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='cylinder_outward_details',
            name='cylinder_return_DC',
            field=models.CharField(unique=True),
        ),
    ]
