# Generated by Django 4.2.1 on 2024-06-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0027_alter_cylinder_inward_details_cylinder_grn_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder_inward_details',
            name='cylinder_po_no',
            field=models.CharField(),
        ),
    ]
