# Generated by Django 4.2.1 on 2024-06-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0028_alter_cylinder_inward_details_cylinder_po_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder_store',
            name='cylinder_sl_r_qr_no',
            field=models.CharField(),
        ),
    ]
