# Generated by Django 4.2.1 on 2024-06-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0029_alter_cylinder_store_cylinder_sl_r_qr_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cylinder_store',
            name='Cylinder_Inward_Table',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='Cylinder_Outward_Table',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_gas_type',
        ),
        migrations.RemoveField(
            model_name='cylinder_store',
            name='cylinder_vendor_name',
        ),
        migrations.DeleteModel(
            name='Cylinder_Inward_Details',
        ),
        migrations.DeleteModel(
            name='Cylinder_Outward_Details',
        ),
        migrations.DeleteModel(
            name='Cylinder_Store',
        ),
    ]
