# Generated by Django 4.2.1 on 2024-06-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0030_remove_cylinder_store_cylinder_inward_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder_Inward_Details',
            fields=[
                ('cylinder_inward_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cylinder_po_no', models.CharField()),
                ('cylinder_po_Date', models.DateField()),
                ('cylinder_GRN_no', models.CharField(unique=True)),
                ('cylinder_GRN_Date', models.DateField()),
                ('cylinder_Invoice_DC_no', models.CharField(unique=True)),
                ('cylinder_description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder_Outward_Details',
            fields=[
                ('cylinder_outward_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cylinder_return_DC', models.CharField(unique=True)),
                ('cylinder_remarks', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder_Store',
            fields=[
                ('cylinder_db_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cylinder_sl_r_qr_no', models.CharField()),
                ('cylinder_scanned_r_submitted_date', models.DateTimeField(default=None, null=True)),
                ('cylinder_scanned_r_submitted_by', models.CharField(max_length=300)),
                ('cylinder_Inward', models.BooleanField(default=False)),
                ('cylinder_Inward_Date', models.DateTimeField(null=True)),
                ('cylinder_Outward', models.BooleanField(default=False)),
                ('cylinder_Outward_Date', models.DateTimeField(null=True)),
                ('cylinder_stocked_in', models.BooleanField(default=False)),
                ('cylinder_stocked_in_Date', models.DateTimeField(null=True)),
                ('cylinder_stock_out', models.BooleanField(default=False)),
                ('cylinder_stock_out_Date', models.DateTimeField(null=True)),
                ('Cylinder_Inward_Table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='QR.cylinder_inward_details')),
                ('Cylinder_Outward_Table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='QR.cylinder_outward_details')),
                ('cylinder_gas_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET, to='QR.cylinder_type_master')),
                ('cylinder_vendor_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET, to='QR.gas_cylinder_vendors_master')),
            ],
        ),
    ]
